apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculator
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: calculator.info
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: calculator
                port:
                  name: http
            path: /
